apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace | default "payments" }}
  labels:
    app.kubernetes.io/name: payments-microservice
    app.kubernetes.io/environment: {{ .Values.environment | default "dev" }}