{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: payments-microservice
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: payments-microservice

  policyTypes:
    - Ingress
    - Egress

  ingress:
    - from:
        - namespaceSelector: {}

      ports:
        - protocol: TCP
          port: {{ .Values.containerPort }}

  egress:
    - {}
{{- end }}
