apiVersion: v1
kind: Service
metadata:
  name: payments-microservice
  namespace: {{ .Values.namespace | default "payments" }}
  labels:
    app: payments-microservice
spec:
  type: {{ .Values.service.type }}
  selector:
    app: payments-microservice
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP