apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders-ebs-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.storage.accessMode }}
  storageClassName: {{ .Values.storage.className }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}