apiVersion: v1
kind: LimitRange
metadata:
  name: payments-limit-range
  namespace: {{ .Values.namespace }}
spec:
  limits:
    - type: Container
      default:
        cpu: {{ .Values.limitRange.defaultCpu }}
        memory: {{ .Values.limitRange.defaultMemory }}
      defaultRequest:
        cpu: {{ .Values.limitRange.defaultRequestCpu }}
        memory: {{ .Values.limitRange.defaultRequestMemory }}