replicaCount: 2

image:
  repository: nginx
  tag: "1.25"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpuUtilization: 60

pdb:
  enabled: true
  maxUnavailable: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi