replicaCount: 4

image:
  repository: nginx
  tag: "1.25"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

hpa:
  enabled: true
  minReplicas: 4
  maxReplicas: 10
  cpuUtilization: 60

pdb:
  enabled: true
  maxUnavailable: 2

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi